# Generated by Django 3.0.4 on 2020-06-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_url_registrar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
        migrations.DeleteModel(
            name='UserFeedBack',
        ),
    ]
